// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/gogurt_vendor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGogurtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGogurtRequest) Reset() {
	*x = GetGogurtRequest{}
	mi := &file_proto_gogurt_vendor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGogurtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGogurtRequest) ProtoMessage() {}

func (x *GetGogurtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gogurt_vendor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGogurtRequest.ProtoReflect.Descriptor instead.
func (*GetGogurtRequest) Descriptor() ([]byte, []int) {
	return file_proto_gogurt_vendor_proto_rawDescGZIP(), []int{0}
}

type Gogurt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Flavor        string                 `protobuf:"bytes,2,opt,name=flavor,proto3" json:"flavor,omitempty"`
	Remaining     int32                  `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Open          bool                   `protobuf:"varint,4,opt,name=open,proto3" json:"open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gogurt) Reset() {
	*x = Gogurt{}
	mi := &file_proto_gogurt_vendor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gogurt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gogurt) ProtoMessage() {}

func (x *Gogurt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gogurt_vendor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gogurt.ProtoReflect.Descriptor instead.
func (*Gogurt) Descriptor() ([]byte, []int) {
	return file_proto_gogurt_vendor_proto_rawDescGZIP(), []int{1}
}

func (x *Gogurt) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Gogurt) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *Gogurt) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *Gogurt) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

var File_proto_gogurt_vendor_proto protoreflect.FileDescriptor

const file_proto_gogurt_vendor_proto_rawDesc = "" +
	"\n" +
	"\x19proto/gogurt_vendor.proto\x12\x06gogurt\"\x12\n" +
	"\x10GetGogurtRequest\"f\n" +
	"\x06Gogurt\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12\x16\n" +
	"\x06flavor\x18\x02 \x01(\tR\x06flavor\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x05R\tremaining\x12\x12\n" +
	"\x04open\x18\x04 \x01(\bR\x04open2G\n" +
	"\fGogurtVendor\x127\n" +
	"\tGetGogurt\x12\x18.gogurt.GetGogurtRequest\x1a\x0e.gogurt.Gogurt\"\x00B\x1dZ\x1bgithub.com/gogurt-rpc/protob\x06proto3"

var (
	file_proto_gogurt_vendor_proto_rawDescOnce sync.Once
	file_proto_gogurt_vendor_proto_rawDescData []byte
)

func file_proto_gogurt_vendor_proto_rawDescGZIP() []byte {
	file_proto_gogurt_vendor_proto_rawDescOnce.Do(func() {
		file_proto_gogurt_vendor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gogurt_vendor_proto_rawDesc), len(file_proto_gogurt_vendor_proto_rawDesc)))
	})
	return file_proto_gogurt_vendor_proto_rawDescData
}

var file_proto_gogurt_vendor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gogurt_vendor_proto_goTypes = []any{
	(*GetGogurtRequest)(nil), // 0: gogurt.GetGogurtRequest
	(*Gogurt)(nil),           // 1: gogurt.Gogurt
}
var file_proto_gogurt_vendor_proto_depIdxs = []int32{
	0, // 0: gogurt.GogurtVendor.GetGogurt:input_type -> gogurt.GetGogurtRequest
	1, // 1: gogurt.GogurtVendor.GetGogurt:output_type -> gogurt.Gogurt
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gogurt_vendor_proto_init() }
func file_proto_gogurt_vendor_proto_init() {
	if File_proto_gogurt_vendor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gogurt_vendor_proto_rawDesc), len(file_proto_gogurt_vendor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gogurt_vendor_proto_goTypes,
		DependencyIndexes: file_proto_gogurt_vendor_proto_depIdxs,
		MessageInfos:      file_proto_gogurt_vendor_proto_msgTypes,
	}.Build()
	File_proto_gogurt_vendor_proto = out.File
	file_proto_gogurt_vendor_proto_goTypes = nil
	file_proto_gogurt_vendor_proto_depIdxs = nil
}
